# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn

      - name: Lint
        if: ${{ always() }}
        run: yarn lint

      - name: Build
        if: ${{ always() }}
        run: yarn build -- --prod

      - name: Test
        if: ${{ always() }}
        run: yarn test -- --configuration=ci

      - name: All Checks Passing!
        if: ${{ success() }}
        run: echo Passing!

      - name: Suspicious...
        if: ${{ failure() }}
        run: echo Suspicious....
